#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#Java applications fix
export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 7
xrandr --output DP-0 --mode 1920x1080 --rate 144.00
bash ~/.config/polybar/launch.sh --blocks
picom -b --experimental-backends &
dunst &
flameshot &
sudo mpd &
feh --bg-fill ~/.config/hypr/geometric.png
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
